<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>CommanderTranslator</AssemblyName>
    <RootNamespace>Gw2CommanderTranslator</RootNamespace>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BlishHUD" Version="1.3.0" ExcludeAssets="runtime;contentFiles;analyzers" />
    <PackageReference Include="System.ComponentModel.Composition" Version="6.0.0" />
  </ItemGroup>
</Project>
